### ISSUE TITLE
The bot misclick

### ISSUE THREAD

**Issue by namhohe** [Frizz925/gbf-autopilot#12]
I am using the bot for current GW and while it run perfectly sometime it misclick on the stage selection. It still can open the ex panel just fine but sometime the random position clicking make the bot click at the bottom edge (the ap spent) and the game doen't allow to do so. The bot just stop doing anything after that. I wonder if there is any way to fix this. Here is the one that it keep misclicking.

![chrome_2018-01-18_13-04-42](https://user-images.githubusercontent.com/25485551/35083190-802285f6-fc50-11e7-849a-2e991fe67237.png)

**Comment by Frizz925** [comment]
Please use the bug report template.
https://github.com/Frizz925/gbf-autopilot/wiki/Bug-Reporting

Also you should try updating the bot to post-rewrite commit. The bot no longer behaves by clicking the quest button and instead uses url now.

**Comment by namhohe** [comment]
I have been using the old dangerous branch for a long time, I tried to install the new bot after you suggested but when I'm installing it show a lot of npm warn depreciated and error, I can't build and config the bot.

**Comment by Frizz925** [comment]
Clone the repository into a new directory and try again.

**Comment by namhohe** [comment]
Okay seems like I can start the bot now, but it's so much different from before, I don't know how to use and not sure if there is any guide.

**Comment by Frizz925** [comment]
I'll write the guide this weekend. Closing for now.
