### ISSUE TITLE
Bot error and stop when using Viramate auto end raid

### ISSUE THREAD

**Issue by pannatatm** [Frizz925/gbf-autopilot#19]
When ever bot do final attack to raid battle and Viramate automatically skip to result screen bot getting error and stop every time. However if game end with skill, bot continue to run perfectly fine. Hotfix is to disable automatically end raid function in Viramate. But for better time saving I'd be glad if this bug fix.

This is error log before bot stopped.
`{"level":"debug","message":"Checking element: .btn-attack-start.display-on","timestamp":"2018-02-02T02:19:47.250Z"}
{"level":"debug","message":"Checking element: .btn-attack-start.display-on","timestamp":"2018-02-02T02:19:47.256Z"}
{"type":"getCombatState","level":"debug","message":"Viramate:","timestamp":"2018-02-02T02:19:47.261Z"}
{"level":"info","message":"Attacking...","timestamp":"2018-02-02T02:19:47.293Z"}
{"level":"debug","message":"Waiting for action result","timestamp":"2018-02-02T02:19:47.293Z"}
{"level":"debug","message":"Clicking with condition: .btn-attack-start.display-on","timestamp":"2018-02-02T02:19:47.295Z"}
{"level":"debug","message":"Checking element: .btn-attack-start.display-on","timestamp":"2018-02-02T02:19:47.295Z"}
{"level":"debug","message":"Clicking element: .btn-attack-start.display-on","timestamp":"2018-02-02T02:19:47.334Z"}
{"level":"debug","message":"Timeout: 750","timestamp":"2018-02-02T02:19:47.829Z"}
{"level":"debug","message":"Action result received","timestamp":"2018-02-02T02:19:48.078Z"}
{"level":"debug","message":"Timeout: 500","timestamp":"2018-02-02T02:19:48.079Z"}
{"level":"debug","message":"Checking element: .btn-attack-start.display-on","timestamp":"2018-02-02T02:19:48.580Z"}
{"level":"debug","message":"Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result","timestamp":"2018-02-02T02:19:48.596Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.620Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.622Z"}
{"type":"getCombatState","level":"debug","message":"Viramate:","timestamp":"2018-02-02T02:19:51.745Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.747Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.750Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.751Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.753Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.755Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.758Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.759Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.760Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.762Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.764Z"}
{"level":"debug","message":"Timeout: 1500","timestamp":"2018-02-02T02:19:51.765Z"}
{"level":"error","message":"Error: {\"type\":\"result\",\"id\":\"HJeR9S-LG\",\"result\":null}","timestamp":"2018-02-02T02:19:51.775Z"}
{"meta":0,"level":"info","message":"AP potion used:","timestamp":"2018-02-02T02:19:51.776Z"}
{"level":"error","message":"Error: {\"type\":\"result\",\"id\":\"HJeR9S-LG\",\"result\":null}","timestamp":"2018-02-02T02:19:51.777Z"}
{"level":"debug","message":"Stopping socket 'PRWs0AbHzBTrf42mAAAB'","timestamp":"2018-02-02T02:19:51.777Z"}
{"level":"info","message":"Autopilot stopped.","timestamp":"2018-02-02T02:19:51.783Z"}
`

**Comment by Frizz925** [comment]
The bot wasn't meant to be used with Viramate's skip raid/quest since it currently doesn't know when the raid has ended with that option enabled. You should disable it for now.

**Comment by Frizz925** [comment]
Also this is more of the bot's logic problem which should belong [here](https://github.com/Frizz925/gbf-autopilot-core/issues). If you feel like this issue should be addressed, feel free to open a new issue there.
