### ISSUE TITLE
info: Waiting for supporter page...

### ISSUE THREAD

**Issue by IrbeinTepes** [Frizz925/gbf-autopilot#23]
### Summary
my server stuck on info: Waiting for supporter page...

### Branch
master

### Commit hash
c4e600a7bdce061883979bffc6f400b2a067fe2f

### Steps to reproduce
clone, install and run

### Game information
- Mobage
- English

### System information
- Windows 10 LTSB
- Resolution + display 1080 16:9
-  Chrome version 66.0.3359.33
- latest
- 3.6

**Comment by Frizz925** [comment]
https://github.com/Frizz925/gbf-autopilot/issues/22
