### ISSUE TITLE
About NIGHTMARE auto-mode

### ISSUE THREAD

**Issue by cccwzi** [Frizz925/gbf-autopilot#3]
Do you have any plan to add the NIGHTMARE mode when it`s available?
And thanks for the autopilot~

**Comment by Frizz925** [comment]
Automatically switching to nightmare battle when it's available? It's been possible to do so from the beginning but it requires a bit more sophisticated scenario writing. I'll create a repository for the scenario examples some time later.

**Comment by Frizz925** [comment]
Check out [this example](https://github.com/Frizz925/gbf-autopilot-scenarios/blob/master/Cerberus.js) for Cerberus farming. It automatically switches context based on whether the Nightmare stage appears on the event page or not.

For a more sophisticated example during Rise of the Beasts event where the bot only farms beast that is on cardinal bonus, you can check [here](https://github.com/Frizz925/gbf-autopilot-scenarios/blob/master/RiseOfTheBeasts.js).
