### ISSUE TITLE
Scenario runs uncorrect

### ISSUE THREAD

**Issue by cccwzi** [Frizz925/gbf-autopilot#4]
Recently I install the gbf-autopilot in my surface(Windows 8.1). It seems good, but when I run the scenario. The mouse will move to wrong position and click. For example the ".btn-ex-raid2" is in the middle of the chrome. Actually the mouse move to the bottom ,click and wait the next action.

**Comment by Frizz925** [comment]
Can I see your scenario script?

**Comment by cccwzi** [comment]
module.exports = [
  ["click", ".btn-ex-raid2"],
  ["click", "[data-quest-id='720361']"], 
  ["support.element", ["earth", [
    2040205000, // tu140
    2040173000, // tu120
    2040059000 // tu80
  ],"5.1"]],

  // turn 1
  ["battle.ca", false],
  // DF w/ DB, Seruel, Uzuki, Albert
  ["battle.skills", [
    "1.1", "1.2", "1.3",
    "1.4", "3.1", "3.1",
	"4.2", 
  ]],
  "battle.attack",

  // turn 2
  ["battle.skill", "4.3"],
  "battle.attack",

  // turn 3
  ["battle.skills", ["2.1","2.3","3.1"]],
  "battle.attack",

  // turn 4
  ["battle.ca", true],
  ["battle.skill", "4.1"],
  "battle.attack",

  // turn 5
  "battle.cycle.attack"
];

**Comment by cccwzi** [comment]
It's the same as my another computer. and I try the different scenario script. But it don`t work.

**Comment by Frizz925** [comment]
I need the following information regarding your environment:
1. What's your screen resolution and text scale?
2. Do you use more than one display?
3. Do you enable bottom navigation bar inside the game?
4. Do you use Mobage account? It does seem non-Mobage account have different elements layout but it's unconfirmed yet.

And finally, try adding these lines before the first click and see if it fixes it:
```
["wait", ".btn-ex-raid2"],
["timeout", 1000],
```

**Comment by cccwzi** [comment]
Thanks!!! It fixed.
As you say it`s the text scale(100% needed).
