### ISSUE TITLE
bot doesn't do anything after start

### ISSUE THREAD

**Issue by namhohe** [Frizz925/gbf-autopilot#6]
I did all the step and when I start the server it still doesn't do anything except start the extension.

![cmd_2017-10-21_17-35-34](https://user-images.githubusercontent.com/25485551/31850938-46a98924-b686-11e7-90e8-bcb0645f6512.png)

It stopped after the last line and nothing happen in the game. I use the AngelHaloNew scenario btw.

![cmd_2017-10-21_18-25-02](https://user-images.githubusercontent.com/25485551/31851300-3ab1d17e-b68d-11e7-8dcf-51e0efb8283f.png)

Here is the screenshot when I try the old halo one.

**Comment by Frizz925** [comment]
Do you use the *master* or *dangerous* branch?

**Comment by namhohe** [comment]
I think I use the master one, I don't know where is the dangerous branch.

**Comment by Frizz925** [comment]
https://github.com/Frizz925/gbf-autopilot/tree/dangerous

If you use Git for pulling the source codes, just run `git checkout dangerous` and re-do the building steps.

**Comment by namhohe** [comment]
Okay I will try it now, I will let you know if it work, thanks.

**Comment by namhohe** [comment]
Thanks, the bot work now, but I still have trouble with the scenarios, I tried both the halo js but at the first step instead of clicking on halo it keep clicking the primarch trials instead, and then when I tried again it just click randomly on screen (sometime crew button, sometime event), is there any game setting I need to do for the bot to run properly?

**Comment by Frizz925** [comment]
You need to set the game size to medium and 100% window zoom and display scaling (Windows 10 display options)
