### ISSUE TITLE
Side Scrolling Scene part

### ISSUE THREAD

**Issue by sklin0er4** [Frizz925/gbf-autopilot#8]
BTW how do I get the SatinFeather scenario to work. Keeps getting stuck at the Side Scrolling Scene part. It doesn't press the first "Skip" button but the second and it also doesn't press the "OK" button whn the item picked up screen pops up.

**Comment by Frizz925** [comment]
You need to change the setting so that the side scrolling scene is completely skipped

**Comment by sklin0er4** [comment]
Ahhh aite aite thx man sry to bother xD
