### ISSUE TITLE
RefillAP turn to true  not  useful

### ISSUE THREAD

**Issue by joezhoucn** [Frizz925/gbf-autopilot#9]
It just stop on the refill AP ,can not refill AP auto.

**Comment by joezhoucn** [comment]
This is my test Scenario for 

module.exports = [
  // Click the ready btn in co-op room
  ["click", ".btn-quest-start.multi.se-quest-start.onm-tc-gbf[data-quest-id='601431']"],
  // use ヨダルラーハ attack 100W
  "battle.auto"
];

and the command server config file is like this 

[Scenario]
Name = Tiguanzi
RefillAP = true

the result is : it will stop on the refill AP page
What's worry?

**Comment by Frizz925** [comment]
Closing this due to outdated issue that may no longer occur on the newer build.
